### ISSUE TITLE
This is not a issue, this is about GitHub organization ID "Surmon"

### ISSUE THREAD

**Issue by surmon-china** [JakubNovak/AutoclickGen#1]
HI! Jakub Novák

@JakubNovak 

I am a developer from GitHub, and my ID is surmon-china. I would like to use my name as the GitHub ID, which is very important for my work. I see that this name is used by an organization of yours. I see that the warehouse in this organization has not been used for a long time, so would you like to transfer this name to me for use? If possible, I would appreciate it very much. , Thank you for reading this letter.

good luck
Surmon

**Comment by JakubNovak** [comment]
Hi, 

I read your post and I have bad news for you. Surmon is the name of a company I founded 5 years ago. I have no intentions to let it go.

Regards, Jakub
